iwd2_mod_dest: "{{ iwd2_path }}"
iwd2_mod_archive_sha256: 15e1d3365f1997fa2110c4ee463544c973386124b1dbcf6b69956e331ba770bf
iwd2_mod_archive_file_path: "{{ role_path }}/files/helm-of-dragon-scales.tar"
iwd2_weidu_installer: "{{ iwd2_mod_dest }}/setup-BBHLMDR.exe"
iwd2_mod_readme_files:
  - "{{ iwd2_path }}/README-BBHLMDR.txt"
iwd2_mod_readme_subdir: "{{ iwd2_mod_readme_dir }}/helm-of-dragon-scales"
iwd2_mod_debug_file: "{{ iwd2_path }}/SETUP-BBHLMDR.DEBUG"
iwd2_mod_cleanup_paths:
  - "{{ iwd2_path }}/BBHLMDR"
  - "{{ iwd2_path }}/SETUP-BBHLMDR.DEBUG"
  - "{{ iwd2_path }}/setup-BBHLMDR.exe"
  - "{{ iwd2_path }}/setup-BBHLMDR.tp2"
  - "{{ iwd2_path }}/README-BBHLMDR.txt"