iwd2_mod_dest: "{{ iwd2_path }}"
iwd2_mod_archive_sha256: 13fb27a39b415b4a0b08bc4918c0e9f25ab7dc10cd80ffd1d87ee72e92d6b81b
iwd2_mod_archive_file_path: "{{ role_path }}/files/comstore.tar"
iwd2_weidu_installer: "{{ iwd2_mod_dest }}/Setup-Comstore.exe"
iwd2_mod_readme_files:
  - "{{ iwd2_path }}/comstore/readme_iwd2store.html"
iwd2_mod_readme_subdir: "{{ iwd2_mod_readme_dir }}/comstore"
iwd2_mod_debug_file: "{{ iwd2_path }}/SETUP-COMSTORE.DEBUG"
iwd2_mod_cleanup_paths:
  - "{{ iwd2_path }}/comstore"
  - "{{ iwd2_path }}/SETUP-COMSTORE.DEBUG"
  - "{{ iwd2_path }}/Setup-Comstore.exe"
  - "{{ iwd2_path }}/Setup-Comstore.tp2"